site_name: PoshBot Docs
repo_url: https://github.com/devblackops/PoshBot
theme: readthedocs
pages:
  - Home: index.md
  - Guides:
    - Quickstart: guides/quickstart.md
    - Message Processing Flow: guides/message-processing.md
    - Configuration: guides/configuration.md
    - Plugins: guides/plugins.md
    - Triggers: guides/triggers.md
    - Scheduled Commands: guides/scheduled-commands.md
    - Scheduled Task: guides/scheduled-task.md
    - Channel Rules: guides/channel-rules.md
    - Command Approvals: guides/command-approvals.md
    - Command Authorization:
      - Overview: guides/command-authorization/overview.md
      - Permissions: guides/command-authorization/permissions.md
      - Roles: guides/command-authorization/roles.md
      - Groups: guides/command-authorization/groups.md
    - Plugin Configuration: guides/plugin-configuration.md
    - Middleware: guides/middleware.md
    - Run Poshbot as a Service: guides/run-poshbot-as-a-service.md
    - Backends:
      - Teams: guides/backends/setup-teams-backend.md
  - Tutorials:
    - Backend Development:
      - Overview: tutorials/backend-development/overview.md
      - Generic Classes:
        - Backend: tutorials/backend-development/backend-class.md
        - Connection: tutorials/backend-development/connection-class.md
        - Message: tutorials/backend-development/message-class.md
        - Person: tutorials/backend-development/person-class.md
        - Room: tutorials/backend-development/room-class.md
    - Plugin Development:
      - Simple: tutorials/plugin-development/simple.md
      - Advanced:
        - Overview: tutorials/plugin-development/advanced/overview.md
        - PoshBot.BotCommand Custom Attribute: tutorials/plugin-development/advanced/poshbot.botcommand-attribute.md
        - Comment-Based Help: tutorials/plugin-development/advanced/comment-based-help.md
        - Custom Responses: tutorials/plugin-development/advanced/custom-responses.md
        - Config-Provided Parameters: tutorials/plugin-development/advanced/config-provided-parameters.md
        - Stateful Data: tutorials/plugin-development/advanced/stateful-data.md
  - Reference:
    - Builtin Commands:
      - General:
        - About: reference/commands/about.md
        - Help: reference/commands/Get-CommandHelp.md
        - Status: reference/commands/Get-PoshBotStatus.md
        - Get-CommandHistory: reference/commands/Get-CommandHistory.md
        - Get-CommandStatus: reference/commands/Get-CommandStatus.md
        - Slap: reference/commands/Slap.md
      - Security:
        - Groups:
          - Add-GroupRole: reference/commands/add-grouprole.md
          - Add-GroupUser: reference/commands/add-groupuser.md
          - Get-Group: reference/commands/get-group.md
          - New-Group: reference/commands/new-group.md
          - Remove-Group: reference/commands/Remove-Group.md
          - Remove-GroupRole: reference/commands/remove-grouprole.md
          - Remove-GroupUser: reference/commands/remove-groupuser.md
          - Update-GroupDescription: reference/commands/Update-GroupDescription.md
        - Permissions:
          - Add-CommandPermission: reference/commands/Add-CommandPermission.md
          - Get-Permission: reference/commands/get-permission.md
          - New-Permission: reference/commands/New-Permission.md
        - Roles:
          - Add-RolePermission: reference/commands/add-rolepermission.md
          - Get-Role: reference/commands/get-role.md
          - New-Role: reference/commands/new-role.md
          - Remove-Role: reference/commands/Remove-Role.md
          - Remove-RolePermission: reference/commands/remove-rolepermission.md
          - Update-RoleDescription: reference/commands/Update-RoleDescription.md
        - Approvals:
          - Approve-PendingCommand: reference/commands/Approve-PendingCommand.md
          - Deny-PendingCommand: reference/commands/Deny-PendingCommand.md
          - Get-PendingCommand: reference/commands/Get-PendingCommand.md
      - Scheduled Commands:
        - Get-ScheduledCommand: reference/commands/Get-ScheduledCommand.md
        - New-ScheduledCommand: reference/commands/New-ScheduledCommand.md
        - Set-ScheduledCommand: reference/commands/Set-ScheduledCommand.md
        - Enable-ScheduledCommand: reference/commands/Enable-ScheduledCommand.md
        - Disable-ScheduledCommand: reference/commands/Disable-ScheduledCommand.md
        - Remove-ScheduledCommand: reference/commands/Remove-ScheduledCommand.md
      - Plugin Management:
        - Get-Plugin: reference/commands/get-plugin.md
        - Find-Plugin: reference/commands/Find-Plugin.md
        - Enable-Plugin: reference/commands/enable-plugin.md
        - Disable-Plugin: reference/commands/disable-plugin.md
        - Install-Plugin: reference/commands/install-plugin.md
        - Remove-Plugin: reference/commands/Remove-Plugin.md
        - Update-Plugin: reference/commands/Update-Plugin.md
    - Modules Functions:
      - Get-PoshBot: reference/functions/get-poshbot.md
      - Get-PoshBotConfiguration: reference/functions/get-poshbotconfiguration.md
      - Get-PoshBotStatefulData: reference/functions/Get-PoshBotStatefulData.md
      - New-PoshBotCardResponse: reference/functions/new-poshbotcardresponse.md
      - New-PoshBotConfiguration: reference/functions/new-poshbotconfiguration.md
      - New-PoshBotFileUpload: reference/functions/New-PoshBotFileUpload.md
      - New-PoshBotInstance: reference/functions/new-poshbotinstance.md
      - New-PoshBotMiddlewareHook: reference/functions/New-PoshBotMiddlewareHook.md
      - New-PoshBotScheduledTask: reference/functions/new-poshbotscheduledtask.md
      - New-PoshBotSlackBackend: reference/functions/new-poshbotslackbackend.md
      - New-PoshBotTeamsBackend: reference/functions/New-PoshBotTeamsBackend.md
      - New-PoshBotTextResponse: reference/functions/new-poshbottextresponse.md
      - Remove-PoshBotStatefulData: reference/functions/Remove-PoshBotStatefulData.md
      - Save-PoshBotConfiguration: reference/functions/save-poshbotconfiguration.md
      - Start-PoshBot: reference/functions/start-poshbot.md
      - Stop-PoshBot: reference/functions/stop-poshbot.md
